config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cmv:
      branch: 146-improve-SQAaaS-score
      repo: https://github.com/cessda/cessda.cmv
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cmv git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-pink-chin.sh
        container: qc.acc_pretty-charcoal-caiman
  QC.Doc:
    repos:
      github.com/cessda/cessda.cmv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-blue-koala.sh
        container: qc.doc_bluesy-flax-insect
      github.com/cessda/cessda.cmv git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-sapphire-harrier.sh
        container: qc.doc_trippy-cerise-bison
      github.com/cessda/cessda.cmv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-charcoal-fish.sh
        container: qc.doc_stinky-aqua-newfoundland
  QC.Lic:
    repos:
      github.com/cessda/cessda.cmv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-copper-camel.sh
        container: qc.lic_scanty-puce-crane
  QC.Met:
    repos:
      github.com/cessda/cessda.cmv cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.homey-cardinal-bonobo.sh
        container: qc.met_trippy-cyan-dragon
  QC.Sty:
    repos:
      github.com/cessda/cessda.cmv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-cerise-falcon.sh
        container: qc.sty_pasty-indigo-wasp
  QC.Ver:
    repos:
      github.com/cessda/cessda.cmv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-chocolate-rat.sh
        container: qc.ver_flimsy-charcoal-burmese
timeout: 5400
